version: '3.4'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME:-Scheduler-laravel}
    tty: true
    restart: unless-stopped
    ports:
      - ${DOCKER_CONTAINER_PORT:-80}:4200
    volumes:
      - ./:/var/www/html/

